export const copy = {
  title: '禅聊',
  tagline: '浏览器直连的无服务器聊天室',
  source: '源码',
  nick: '昵称',
  room: '房间名',
  password: '房间口令（可选）',
  passwordHint: '口令会参与房间隔离，不会发到任何自建服务器。分享链接时可选择是否带上。',
  strategy: '公共信令',
  torrent: 'WebTorrent Tracker',
  nostr: 'Nostr 中继',
  join: '进入房间',
  lobbyHint: '同一房间名 + 同一信令 + 同一口令的浏览器，会经公共 Tracker / 中继交换 SDP，随后走 WebRTC DataChannel 直连。',
  recent: '最近房间',
  emptyRecent: '还没有最近房间',
  share: '复制链接',
  shareWithKey: '复制含口令链接',
  leave: '离开',
  send: '发送',
  placeholder: '写下一条消息，Enter 发送，Shift+Enter 换行',
  members: '在线节点',
  you: '你',
  waiting: '还没有其他浏览器。把链接发给同伴，或再开一个窗口加入同一房间。',
  copied: '已复制',
  webrtcMissing: '当前环境没有 WebRTC。请使用最新版 Chrome、Firefox、Safari 或 Edge，并确保页面处于 HTTPS。',
  insecure: 'WebRTC 需要安全上下文。请通过 HTTPS（例如 GitHub Pages）或 localhost 打开。',
}
