export const copy = {
  title: '禅聊',
  tagline: '无服务器 · 浏览器直连',
  source: '源码',
  nick: '昵称',
  room: '房间',
  password: '口令',
  passwordHint: '口令只隔离房间，不会上传。',
  strategy: '信令',
  torrent: 'Tracker',
  nostr: 'Nostr',
  join: '加入',
  more: '更多选项',
  lobbyHint: '同一房间即可直连，无需账号。',
  recent: '最近',
  emptyRecent: '还没有房间',
  share: '分享',
  shareWithKey: '含口令',
  leave: '大厅',
  send: '发送',
  placeholder: '发消息',
  members: '在线',
  you: '你',
  waiting: '分享链接给同伴',
  copied: '已复制',
  webrtcMissing: '需要支持 WebRTC 的浏览器，并用 HTTPS 打开。',
  insecure: '需要 HTTPS 或 localhost。',
  switch: '切换房间',
  addRoom: '加入房间',
  stamps: '表情',
  kaomoji: '颜文字',
  emoji: '表情',
  people: '成员',
}