export const APP_ID = 'zenchat.andyccr.v1'
export const APP_NAME = 'ZenChat'
export const PROTOCOL_VERSION = 1
export const MAX_NICK_LENGTH = 24
export const MAX_ROOM_LENGTH = 64
export const MAX_MESSAGE_LENGTH = 4000
export const MAX_RECENT_ROOMS = 10
export const MAX_LOG_LINES = 200
export const MAX_SEEN_IDS = MAX_LOG_LINES * 2
export const DEFAULT_ROOM = 'lobby'
export const TYPING_TTL_MS = 2500
export const TYPING_THROTTLE_MS = 1800
export const HELLO_INTERVAL_MS = 25_000
export const RELAY_POLL_MS = 5000
export const SOURCE_URL = 'https://github.com/Andyccr/ZenChat'
export const PAGES_URL = 'https://andyccr.github.io/ZenChat/'
